import json
import tempfile
import unittest
from pathlib import Path

from scripts.render_current_research_state import render_body


class CurrentResearchStateTest(unittest.TestCase):
    def test_dashboard_is_generated_from_committed_machine_state(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "research/autonomous").mkdir(parents=True)
            (root / "research/m6-incumbent-structured-diagnostic").mkdir(parents=True)
            (root / "research/weak-domain-funnel-v1").mkdir(parents=True)
            (root / "research/autonomous/state.json").write_text(
                json.dumps(
                    {
                        "state_version": "autonomous-state-v1",
                        "incumbent_checkpoint": "checkpoints/incumbent.pt",
                        "incumbent_gci_v1": 42.5,
                        "difficulty": 1,
                        "cycle_index": 101,
                        "autonomy_status": "research_hold",
                        "circuit_breaker": {"active": True, "reason": "test hold"},
                    }
                ),
                encoding="utf-8",
            )
            (root / "research/m6-incumbent-structured-diagnostic/latest.json").write_text(
                json.dumps(
                    {
                        "diagnostic": {
                            "task_count": 60,
                            "free_generation": {"strict_correct": 2, "termination_rate": 1.0},
                            "oracle_context_greedy": {
                                "token_accuracy": 0.25,
                                "quartile_position_accuracy": [0.4, 0.3, 0.2, 0.1],
                            },
                            "structured_semantics": {"valid_json_rate": 0.9},
                        }
                    }
                ),
                encoding="utf-8",
            )
            (root / "research/weak-domain-funnel-v1/latest.json").write_text(
                json.dumps(
                    {
                        "workflow_run_id": 123,
                        "gate_decision": "reject",
                        "winner_variant": "structured-prefix-next-v1",
                        "baseline_gci_v1": 42.5,
                        "candidate_gci_v1": 44.0,
                        "adopted": False,
                        "screening_processed_tokens": 1_200_000,
                    }
                ),
                encoding="utf-8",
            )
            body = render_body(root)
            self.assertIn("GCI-v1: **42.5000**", body)
            self.assertIn("research_hold", body)
            self.assertIn("test hold", body)
            self.assertIn("oracle-context next-token accuracy: **25.00%**", body)
            self.assertIn("late-quartile oracle accuracy: **10.00%**", body)
            self.assertIn("structured-prefix-next-v1", body)
            self.assertIn("42.5000 -> 44.0000", body)
            self.assertIn("Generated by `scripts/render_current_research_state.py`", body)

    def test_dashboard_tolerates_absent_optional_research_results(self):
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            (root / "research/autonomous").mkdir(parents=True)
            (root / "research/autonomous/state.json").write_text(
                json.dumps(
                    {
                        "state_version": "autonomous-state-v1",
                        "incumbent_checkpoint": "checkpoints/incumbent.pt",
                        "incumbent_gci_v1": 31.6667,
                        "difficulty": 1,
                        "cycle_index": 5,
                        "autonomy_status": "running",
                        "circuit_breaker": {"active": False},
                    }
                ),
                encoding="utf-8",
            )
            body = render_body(root)
            self.assertIn("GCI-v1: **31.6667**", body)
            self.assertIn("#246", body)
            self.assertNotIn("Latest weak-domain funnel result", body)


if __name__ == "__main__":
    unittest.main()
